[package]
name = "revenant"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
cgmath = "0.18.0"
freetype-rs = "0.32.0"
gl = "0.14.0"
glfw = "0.50.0"
image = "0.24.5"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
