name: Rust

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install CMake
        run: sudo apt-get install cmake
      - name: Install libxrandr Development Package
        run: sudo apt-get install -y libxrandr-dev
      - name: Install libxinerama Development Package
        run: sudo apt-get install -y libxinerama-dev
      - name: Install libxcursor Development Package
        run: sudo apt-get install -y libxcursor-dev
      - name: Install libxi Development Package
        run: sudo apt-get install -y libxi-dev
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
